image: apihackers/twine

stages:
  - deploy

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  script:
    - python setup.py sdist
    - twine upload dist/*
