image: pypiserver/pypiserver

stages:
  - deploy

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  script:
    - twine upload dist/*
