image: docker.km3net.de/base/python:3

stages:
  - deploy

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  script:
    - pip install -U twine
    - python setup.py sdist
    - twine upload --verbose dist/*
